---
- name: add rabbitmq virtual host for sensu
  sudo: True
  shell: rabbitmqctl add_vhost /sensu
  ignore_errors: yes 
- shell: rabbitmqctl add_user sensu pass
  sudo: True
  ignore_errors: yes 
- shell: rabbitmqctl set_permissions -p /sensu sensu ".*" ".*" ".*"
  sudo: True
  ignore_errors: yes 
- name: Configure Sensu connection to Redis
  copy: src=redis.json dest=/etc/sensu/conf.d/redis.json
- name: Configure Sensu API
  copy: src=api.json dest=/etc/sensu/conf.d/api.json
- name: Enable services to start automatically
  shell: update-rc.d sensu-server defaults
  sudo: true
  shell: update-rc.d sensu-api defaults
  sudo: true
- name: Start the Sensu services
  service: name=sensu-server state=started
  sudo: True
- service: name=sensu-api state=started
  sudo: True
