---
- name: download sensu key
  shell: wget -q http://repos.sensuapp.org/apt/pubkey.gpg -O- | sudo apt-key add -
- name: add sensu to sources
  shell: echo "deb   http://repos.sensuapp.org/apt sensu main" | sudo tee -a /etc/apt/sources.list.d/sensu.list
- name: update apt cache
  apt: update_cache=yes
- name: install sensu
  apt: name=sensu state=latest
- name: Copy rabbitmq ssl keys into sensu ssl config
  shell: mkdir -p /etc/sensu/ssl && cp /tmp/ssl_certs/client/cert.pem /tmp/ssl_certs/client/key.pem /etc/sensu/ssl
  sudo: true
- name: Configure Sensu connection to RabbitMQ
  copy: src=rabbitmq.json dest=/etc/sensu/conf.d/rabbitmq.json
- shell: update-rc.d sensu-client defaults
  sudo: true
