---
- name: Install Sensu Client with Open Socket
  hosts: all
  sudo: True
  vars:
    - rabbitmq_host: 192.168.50.4
    - rabbitmq_port: 5671
    - rabbitmq_vhost: /sensu
    - rabbitmq_user: sensu
    - rabbitmq_pass: pass
  roles:
    - common
    - sensu-common
    - sensu-client
