---
- name: Install Sensu Client with Open Socket
  hosts: all
  sudo: True
  vars:
    - rabbitmq_host: 52.74.28.241
    - rabbitmq_port: 5671
    - rabbitmq_vhost: /sensu
    - rabbitmq_user: sensu
    - rabbitmq_pass: pass
  roles:
    - common
    - sensu
    - sensu-client
    - mock-validation-tracker
